Merge Develop to Main (#1790)
* merge main -> dev (#1300)

* Automated dotnet-format update (#1296)

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* https://github.com/xamarin/XamarinCommunityToolkit/issues/1292 (#1301)

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Andrei <andrei.misiukevich@gmail.com>

* Expander: Add touch capture view + common animation length / easing properties (#1349)

* Added base animation props

* Added TouchCaptureView property

* Updated light dismiss xml docs (#1366)

* [Converter] Added IsInRangeConverter (#1158)

* Added IsBetweenConverter

* Renamed to IsInRangeConverter

* Added Sample Page

* Added IsInRangeConverterViewModel

* Updated UnitTests

* Cleanup

* Removed RevertResult

* Implemented BindableObjectExtension

* Made ValueConverterExtension inherited from BindableObject

Co-authored-by: Brandon Minnick <13558917+brminnick@users.noreply.github.com>
Co-authored-by: Javier Suárez <javiersuarezruiz@hotmail.com>
Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>
Co-authored-by: Andrei <andrei.misiukevich@gmail.com>
Co-authored-by: Gerald Versluis <gerald.versluis@microsoft.com>

* Drawing View (#740)

* DrawingView (#468)

* DrawingView control, samples, documentation

* fix build issues

Co-authored-by: Vladislav Antonyuk <vlad.antonyuk@outlook.com>
Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>

* fixed codestyle on Android renderer

* GTK renderer adjustments

* iOS renderer adjustments

* MacOS renderer adjustments

* TIzen rendere adjustments

* UWP renderer adjustments

* WPF tests

* Fixed merge conflict

* Fixed wpf stackoverflow exception

* fixed iOS leaks

* revert toast change

* removed wpf implementations

* root sample page to WelcomePage

* removed DrawingView ctor from MainWindow

* removed drawing instructions from readme

* Update README.md

* Drawing View - Fix nullable, add doc to the public method (#1293)

* Fix nullable, add doc to the public method. add WPF

* Remove WPF renderer from the library.

* Change exception message for small images, fix nullable

* return null instead of exception (#1339)

Co-authored-by: Vladislav Antonyuk <33021114+VladislavAntonyuk@users.noreply.github.com>
Co-authored-by: Vladislav Antonyuk <vlad.antonyuk@outlook.com>
Co-authored-by: Brandon Minnick <13558917+brminnick@users.noreply.github.com>
Co-authored-by: Javier Suárez <javiersuarezruiz@hotmail.com>
Co-authored-by: Gerald Versluis <gerald.versluis@microsoft.com>

* Added IsLightDismissed to PopupDismissedEvent (#1362)

* Added IsLightDismissed to PopupDismissedEvent; Fixed Dismissed event so it fires when light dismissed for UWP and Android

* Removing stale comments

* Added Opened event handler to set isOpen to true when Popup displays

* Fixed event cleanup code to unregisterd Closing event

Co-authored-by: Gerald Versluis <gerald.versluis@microsoft.com>

* Fix Android crashes if Bitmap is small, Fix iOS drawing in scrollView (#1421)

* Add StatusBarEffect and NavigationBarEffect classes to manage their color and style (#812)

* Sample Android implementation (doesn't work)

* Update to Android 11

* Add OnElementPropertyChanged

* Refactor GetWindow a bit

* Add dummy implementations for iOS and UWP

* Update Xamarin.CommunityToolkit.csproj

* Update Xamarin.CommunityToolkit.csproj

* Fixed get Activity property

* Update PlatformBarStyle.android.cs

* Remove NavigationBar bits

* Make SetStatusBarColor available on API 23+

* Make StatusBar white for demo app

* Rename BarStyle to Window

* Fix spaces

* Revert "Update to Android 11"

This reverts commit 656f0d05b1f49321316ae8762cdc8f6a1f4a4d39.

* Update Xamarin.CommunityToolkit.csproj

* Rename Window to WindowEffect

* Revert Android 11 API support

* Set status bar style in app.xaml

* Replaced Window with WindowEffect is other places

* Remove Detached implementation

* Add WindowEffectAndroid for navigation bar stuff

* Refactor SetBarStyle methods

* Add UWP implementation

* Add iOS implemetation (not tested)

* Use switch expression

* Add `#region` to specify Linker Work-Around

* Rename WindowEffect to StatusBarEffect

* Rename WindowEffectAndroid to PlatformNavigationBarEffect

* Fix nullability errors

* Commit to rerun tests

* Revert "Commit to rerun tests"

This reverts commit f207c74c7b05872b988bf05a39d70d265377fc44.

* Add sample page

* Fix default is not applied on Android

* Fix radiobutton name on sample page

* Add android specific NavigationBar class

* Remove unneeded null checks

* Coverted StatusBarEffect to static class

* Improve description

* Update EffectIds.shared.cs

* Remove unneeded activity parameter

* Refactor StatusBar.uwp

* Setting view model in XAML

* Update NavigationBar.android.cs

* Make StatusBar style setters accessible from C#

* Add XML documentation

* Remove unrelated code

* Move constant outside the loop

* Add logs if bar style is not supported

* Remove LightContent case

* Commit to rerun build

* Revert "Commit to rerun build"

This reverts commit a49e18f50a7759cbc154a669b6f48877ddb4c1ac.

* Revert "Revert "Commit to rerun build""

This reverts commit c9b3d5b647a992596d585c5ea94b8ef2635c2761.

* Revert "Revert "Revert "Commit to rerun build"""

This reverts commit 7152b252b8212b2e713c239c2d84a812044fec11.

* Change Debug to Trace

* Replace Trace with Log

* Update src/CommunityToolkit/Xamarin.CommunityToolkit/PlatformConfiguration/AndroidSpecific/NavigationBar.shared.cs

Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>

* Update src/CommunityToolkit/Xamarin.CommunityToolkit/PlatformConfiguration/AndroidSpecific/NavigationBar.shared.cs

Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>

* Revert "Update src/CommunityToolkit/Xamarin.CommunityToolkit/PlatformConfiguration/AndroidSpecific/NavigationBar.shared.cs"

This reverts commit c56f02bf76e5572d05092f6f4c682fe4301f8bb8.

* Revert "Update src/CommunityToolkit/Xamarin.CommunityToolkit/PlatformConfiguration/AndroidSpecific/NavigationBar.shared.cs"

This reverts commit 6d37b505043a8db067ca2247caea1b7d8babc3da.

* Move enums to sepparate files

* Replace linq with methods

* Update UpdateStatusBarAppearance to support iOS 13

Co-Authored-By: Daniel Christmas <1112585+justadaniel@users.noreply.github.com>

* View controller-based status bar appearance: No

Co-Authored-By: Daniel Christmas <1112585+justadaniel@users.noreply.github.com>

* Commit to rerun tests

* Update EffectsGalleryViewModel.cs

* Move files to Effects folder

* Converted BarStyle to effects

* Update sample app

* Drop Windows Mobile support

* Get activity from control

* Update NavigationBarEffect.shared.cs

* Commit to rerun tests

* refactoring ios

* removed UWP linker hack

We don't need it for UWP since we don't have a Linker for it

* Removed not needed properties

* Remove not needed null checks

* Remove using

* Commit to rerun tests

* Moved NavigationBarEffect to use the platformspecific API

* Updated the sample

* Fix test

* Little better styling

Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>
Co-authored-by: Brandon Minnick <13558917+brminnick@users.noreply.github.com>
Co-authored-by: Javier Suárez <javiersuarezruiz@hotmail.com>
Co-authored-by: Daniel Christmas <1112585+justadaniel@users.noreply.github.com>
Co-authored-by: Gerald Versluis <gerald@verslu.is>

* Drawing view fixes (#1459)

* Set default line LineColor as black, Fix ClearOnFinish

* Fix SmoothPath issue, update macOS renderer, update sample

* Fix tizen build

* Snackbar corner radius (#1437)

* Snackbar/Toast CornerRadius

* iOS, macOS

* UWP

* WPF

* Update sample, add NativeSnackBar.ios.macos.cs

* Fix ios, macos corner radius

* Update default corner radius to 4

```xml
 <shape android:shape="rectangle"
    xmlns:android="http://schemas.android.com/apk/res/android">
    <solid android:color="#323232"/>
    <corners android:radius="4dp"/>
</shape>
```

* Set CornerRadius to 10

* Set CornerRadius to 10

* Use default Corner Radius if not specified

Co-authored-by: Brandon Minnick <13558917+brminnick@users.noreply.github.com>
Co-authored-by: Gerald Versluis <gerald.versluis@microsoft.com>

* Added missing using System (#1483)

* [MacOS] Added MediaElement implementation (#1488)

Co-authored-by: Yuriy Holembyovskyy <yuriy.holembyovskyy@gmail.com>
Co-authored-by: Gerald Versluis <gerald.versluis@microsoft.com>

* Drawing view multi line (#1475)

* DrawingView MultiLine

WPF, UWP

* Android

* GTK, Tizen

* iOS, macOS

* DrawingViewService Get Stream from lines

* added missing System using

* Add GetImageStream

* Fix tests

* Add description to switches

* Styling and comments

* DrawingLineCompletedEventArgs

* Add summary, Add tests

Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>
Co-authored-by: Gerald Versluis <gerald.versluis@microsoft.com>
Co-authored-by: Gerald Versluis <gerald@verslu.is>

* [Bug] Fixed CameraView Linker issue (#1503)

* Fixed CameraView linker issue

* Added Preserve Conditional

* Added test case

Co-authored-by: Gustavo Oliveira <gustavo.oliveira@inspectrealestate.com.au>
Co-authored-by: Andrei <andrei.misiukevich@gmail.com>
Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>

* [iOS | Android] TextSwitcher + [iOS] ImageSwitcher (#1422)

* Added text switcher

* Added text switcher sample

* Address comments

* Update src/CommunityToolkit/Xamarin.CommunityToolkit/Views/ViewSwitcher/TextSwitcherRenderer.android.cs

Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>

* Update src/CommunityToolkit/Xamarin.CommunityToolkit/Views/ViewSwitcher/TextSwitcherRenderer.android.cs

Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>

* address comment

* fixed build

* fixed typo

* Update src/CommunityToolkit/Xamarin.CommunityToolkit/Views/ViewSwitcher/TextSwitcherRenderer.android.cs

Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>

* cached sdk int

* Fixed warnings

Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>

* iOS, macOS - Clean DrawingView on Lines clean (#1520)

* [Bug] Fixed CameraView crash on FlashMode Torch (#1522)

* Update FormsCameraView.ios.cs

Fixed CameraView crashing in Torch FlashMode

* Update src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/iOS/FormsCameraView.ios.cs

Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>

Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>
Co-authored-by: Andrei <andrei.misiukevich@gmail.com>

* Consolidate our XCT platform class (#1559)

* Moved and renamed ToolkitPlatform to XCT inside helpers folder

* replaced all SDK version calls to XCT cached one

* removed unecessary space

* Added a cache to the iOS version

* [Bug] Fixed CameraView Shutter not responding (#1535)

* Fixed CameraView Shutter not responding

* Fixed Merge conflict

* Update FormsCameraView.ios.cs

Removed unnecessary code

* Update FormsCameraView.ios.cs

Co-authored-by: Andrei <andrei.misiukevich@gmail.com>
Co-authored-by: Gerald Versluis <gerald@verslu.is>
Co-authored-by: Gerald Versluis <gerald.versluis@microsoft.com>

* Added Speed Property to mediaelement (#1570)

* Added Speed control for MediaElement in iOS and Android

* Added Update Speed inside Play Method so after pausing and playing speed will be remembered

* Added Sample for speed

* Update src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/Android/MediaElementRenderer.android.cs

Co-authored-by: Andrei <andrei.misiukevich@gmail.com>

* Update src/CommunityToolkit/Xamarin.CommunityToolkit/Views/MediaElement/Android/MediaElementRenderer.android.cs

Co-authored-by: Andrei <andrei.misiukevich@gmail.com>

* Changed Speed Property binding mode to oneway and removed un necessary property Speed from IMediaElementController

* Added Speed control for MediaElement in iOS and Android

* Changed Speed Property binding mode to oneway and removed un necessary property Speed from IMediaElementController

Co-authored-by: Aswin P G <aswinpg@outlook.in>
Co-authored-by: Andrei <andrei.misiukevich@gmail.com>

* Utc to local string converter (#1555)

* Added UtcDateTimeToLocalStringConverter with page to test.

* Tests class added

* Refactored Tests

* Added some additional tests

* Added new converter to the Converters gallery

* Minor fixes

* Code tidy.

* Some passing test.

* Resolves Error CS8625.

* All tests passing

* Suggest changes including:
Moved BindableProperty to top of class.
IsValidDateFormat uses DateTime.TryParse rather then DateTime.Parse.
Removed is string type check for DateTimeFormat.

* Update src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/UtcDateTimeToLocalStringConverter.shared.cs

* Update src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/UtcDateTimeToLocalStringConverter.shared.cs

* Update src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/UtcDateTimeToLocalStringConverter.shared.cs

* Update src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/UtcDateTimeToLocalStringConverter.shared.cs

* removed private from method

Co-authored-by: Andrei <andrei.misiukevich@gmail.com>
Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>

* Update RangeSlider.shared.cs (#1545)

Co-authored-by: Gerald Versluis <gerald.versluis@microsoft.com>
Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>

* Removed unused code (#1586)

Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>

* [Enhancement][Converter] Add Expression property to MathExpressionConverter and MultiMathExpressionConverter (#1609)

* Added Expression parameter

* Fixed Expression property declaration

* Updated sample page

* Added Tests

Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>

* [Bug] [XCT.Sample] Fixed ContentPages BackgroundColor (#1595)

* Removed SetAppThemeColor

* Move `BasePage` to `Pages` folder

* Handle Null Dereferences introduced in .NET 6

Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>
Co-authored-by: Andrei <andrei.misiukevich@gmail.com>
Co-authored-by: Brandon Minnick <13558917+brminnick@users.noreply.github.com>

* CornerRadiusEffect (#1316)

* CornerRadiusEffect added

* cosmetics

* Safe corner radius value impl

* nullable fix

* reduce to one linq call

Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>

* Effect replaced by event subscription

* Update src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/CornerRadius/CornerRadiusEffect.shared.cs

* C#9 cleanup

* removed extra )

* Update src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/CornerRadius/CornerRadiusEffect.shared.cs

Co-authored-by: Javier Suárez <javiersuarezruiz@hotmail.com>
Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>
Co-authored-by: Andrei <andrei.misiukevich@gmail.com>
Co-authored-by: Brandon Minnick <13558917+brminnick@users.noreply.github.com>

* Update dotnet-format-daily.yml

* MauiCompat Fix for preview 12 (#1792)

* Fix for preview 12

* Allow Prerelease of .NET 6

* Add `--include-previews` to Install .NET MAUI Workload

* Specify .NET v6.0.2

* Install Nightly .NET Build

* Update azure-pipelines.yml

* Update azure-pipelines.yml

* Update azure-pipelines.yml

* Update azure-pipelines.yml

* Update azure-pipelines.yml

* Update azure-pipelines.yml

* Update azure-pipelines.yml

* Update azure-pipelines.yml

* dotnet install with script

* Update azure-pipelines.yml

* install using script

* Update azure-pipelines.yml

* set version

* remove dir

Co-authored-by: Brandon Minnick <13558917+brminnick@users.noreply.github.com>

* Match Visual Studio 2022 .NET 6.0.2 Preview Version

* Update azure-pipelines.yml

Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Andrei <andrei.misiukevich@gmail.com>
Co-authored-by: Gerald Versluis <gerald@verslu.is>
Co-authored-by: Andrew Hoefling <andrewh@fileonq.com>
Co-authored-by: Gustavo Oliveira <gu.ol@hotmail.com>
Co-authored-by: Javier Suárez <javiersuarezruiz@hotmail.com>
Co-authored-by: Gerald Versluis <gerald.versluis@microsoft.com>
Co-authored-by: Vladislav Antonyuk <33021114+VladislavAntonyuk@users.noreply.github.com>
Co-authored-by: Vladislav Antonyuk <vlad.antonyuk@outlook.com>
Co-authored-by: Maksym Koshovyi <maximkoshevoi61@gmail.com>
Co-authored-by: Daniel Christmas <1112585+justadaniel@users.noreply.github.com>
Co-authored-by: Yuriy Holembyovskyy <yholembyovskyy@gmail.com>
Co-authored-by: Yuriy Holembyovskyy <yuriy.holembyovskyy@gmail.com>
Co-authored-by: Gustavo Oliveira <gustavo.oliveira@inspectrealestate.com.au>
Co-authored-by: Aswin P G <aswinpg@outlook.in>
Co-authored-by: Leonard <leojharris@hotmail.com>
Co-authored-by: Yann Zahringer Ferrando <YZahringer@users.noreply.github.com>