Utc to local string converter (#1555)
* Added UtcDateTimeToLocalStringConverter with page to test.

* Tests class added

* Refactored Tests

* Added some additional tests

* Added new converter to the Converters gallery

* Minor fixes

* Code tidy.

* Some passing test.

* Resolves Error CS8625.

* All tests passing

* Suggest changes including:
Moved BindableProperty to top of class.
IsValidDateFormat uses DateTime.TryParse rather then DateTime.Parse.
Removed is string type check for DateTimeFormat.

* Update src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/UtcDateTimeToLocalStringConverter.shared.cs

* Update src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/UtcDateTimeToLocalStringConverter.shared.cs

* Update src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/UtcDateTimeToLocalStringConverter.shared.cs

* Update src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/UtcDateTimeToLocalStringConverter.shared.cs

* removed private from method

Co-authored-by: Andrei <andrei.misiukevich@gmail.com>
Co-authored-by: Pedro Jesus <pedrojesus.cefet@gmail.com>